name: geog313-final-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab=4.2.5
  - pystac-client=0.7.5
  - leafmap=0.38.5
  - matplotlib
  - dask=2024.9.1
  - distributed=2024.9.1
  - stackstac=0.5.0
  - numpy
  - pandas
  - xarray
  - rasterio
  - geopandas
  - shapely
  - seaborn
  - scikit-learn
  - zarr
  - fsspec
  - s3fs
  - pyproj
  - fiona
  - pystac
  - pip:
      - planetary-computer
      - pystac-client
      - stackstac
