name: geog313-final-project
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python + scientific stack
  - python=3.11
  - numpy
  - pandas
  - xarray
  - rasterio
  - geopandas
  - shapely
  - matplotlib
  - scipy
  - scikit-learn
  - jupyterlab=4.2.5
  - dask=2024.9.1
  - distributed=2024.9.1
  - stackstac=0.5.0
  - leafmap=0.38.5
  - fiona
  - pyproj
  - pip  # required to install PyPI-only packages

  # PyPI-only packages
  - pip:
      - planetary-computer
      - pystac
      - zarr
      - fsspec
      - s3fs
      - seaborn
